videoservice/blog/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (
    posts_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    PostLikeToggle,
    PostLikeAPIToggle,
    newsletter_signup,
    newsletter_unsubscribe,
    search_list_view,
)



app_name = 'blog'


urlpatterns = [
    url(r'^$', posts_list, name='blog'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like'),
    url(r'^api/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like_api'),
    url(r'sign_up/$', newsletter_signup, name='newsletter_signup'),
    url(r'unsubscribe/$', newsletter_unsubscribe, name='newsletter_unsubscribe'),
    url(r'^searchlist$', search_list_view, name='search_list'),
]

videoservice/memberships/urls.py
from django.urls import path
from django.conf.urls import url
from allauth.account.views import LoginView, SignupView
from .views import (
	MembershipSelectView,
	PaymentView,
	updateTransactionRecords,
	my_membership_view,
	cancelSubscription,
	user_logout_view,
	profile_view,
	accept_friend_request,
	send_friend_request,
	delete_friend_request,
	cancel_friend_request,
	delete_friend,
	)

app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
	path('signup/', SignupView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', user_logout_view, name='logout'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransactionRecords, name='update-transactions'),
	path('my_membership/', my_membership_view, name='my_membership'),
	path('cancel/', cancelSubscription, name='cancel'),
	url(r'^(?P<slug>[\w-]+)/$', profile_view, name='profile-view'),
	url(r'^friend-request/send/(?P<id>[\w-]+)/$', send_friend_request),
    url(r'^friend-request/cancel/(?P<id>[\w-]+)/$', cancel_friend_request),
    url(r'^friend-request/accept/(?P<id>[\w-]+)/$', accept_friend_request),
    url(r'^friend-request/delete/(?P<id>[\w-]+)/$', delete_friend_request),
	url(r'^friends/delete/(?P<id>[\w-]+)/$', delete_friend),
]

videoservice/courses/models.py
from django.db import models
from memberships.models import Membership
from django.urls import reverse


def get_membership_instance(type):
    qs = Membership.objects.filter(membership_type=type)
    if qs.exists():
        return qs[0]
    return None


class Course(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    description = models.TextField()
    image = models.ImageField(upload_to="course_img", null=True, blank=True)
    allowed_membership = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def lessons(self):  # grouping lessons with a course in a specific order
        return self.lesson_set.all().order_by('position')

    class Meta:
        db_table = 'Course'


class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    position = models.IntegerField()
    video_url = models.FileField(
        upload_to='videos/%Y/%m/$D/', null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail', kwargs={'course_slug': self.course.slug, 'lesson_slug': self.slug})

    class Meta:
        db_table = 'Lesson'

videoservice/memberships/forms.py
from django import forms

from .models import UserMembership


class UserForm(forms.ModelForm):

    class Meta:
        model = UserMembership
        fields = ('first_name', 'last_name', 'bio',
                  'location', 'birth_date', 'avatar')


class AvatarChangeForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs = {
            'class': 'form-control'
        }
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs = {
            'class': 'form-control'
        }
    ))
    location = forms.CharField(widget=forms.TextInput(
        attrs = {
            'class': 'form-control'
        }
    ))
    bio = forms.CharField(widget=forms.Textarea(
        attrs = {
            'class': 'form-control'
        }
    ))

    class Meta:
        model = UserMembership
        fields = ('avatar', 'first_name', 'last_name', 'bio', 'location')

videoservice/memberships/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.db import IntegrityError, transaction
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.template import RequestContext
from django.views.generic import ListView
from django.urls import reverse
from blog.models import Post
from allauth.account.views import SignupView, LoginView
from .models import Membership, UserMembership, Subscription, FriendRequest
from .forms import UserForm, AvatarChangeForm
import stripe


User = get_user_model()

@login_required
def user_logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')


@login_required
def my_membership_view(request):
    user_membership = get_user_membership(request)
    user_subscription = get_user_subscription(request)
    user_posts = Post.objects.filter(author=user_membership)
    users = UserMembership.objects.exclude(user=request.user)

    p = UserMembership.objects.filter(user=request.user).first()
    sent_friend_requests = FriendRequest.objects.filter(from_user=p.user)
    rec_friend_requests = FriendRequest.objects.filter(to_user=p.user)

    friends = p.friends.all()


    avatar_form = AvatarChangeForm()
    if request.method == "POST":
        avatar_form = AvatarChangeForm(request.POST, request.FILES)
        if avatar_form.is_valid():
            user_membership.avatar = avatar_form.cleaned_data.get('avatar')
            user_membership.first_name = avatar_form.cleaned_data.get('first_name')
            user_membership.last_name = avatar_form.cleaned_data.get('last_name')
            user_membership.bio = avatar_form.cleaned_data.get('bio')
            user_membership.location = avatar_form.cleaned_data.get('location')
            user_membership.save()
    context = {
        'users': users,
		'user_membership': user_membership,
        'friends': friends,
        'sent_friend_requests': sent_friend_requests,
        'rec_friend_requests': rec_friend_requests,
        'user_subscription': user_subscription,
        'posts': user_posts,
        'avatar_form': avatar_form
    }
    return render(request, "memberships/my_membership.html", context)


def get_user_membership(request):
    user_membership_qs = UserMembership.objects.filter(user=request.user)
    if user_membership_qs.exists():
        return user_membership_qs.first()
    return None


def get_user_subscription(request):
    # filter subscription by user memberships
    user_subscription_qs = Subscription.objects.filter(
        user_membership=get_user_membership(request))  # FK on Subscription
    if user_subscription_qs.exists():
        user_subscription = user_subscription_qs.first()
        return user_subscription
    return None

"""
Gets the users current membership from the session at
the bottom of MembershipSelectView
"""
def get_selected_membership(request):
    membership_type = request.session['selected_membership_type']
    selected_membership_qs = Membership.objects.filter(
        membership_type=membership_type)
    if selected_membership_qs.exists():
        return selected_membership_qs.first()
    return None


class MembershipSelectView(ListView):
    model = Membership

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        current_membership = get_user_membership(self.request)
        context['current_membership'] = str(current_membership.membership)
        return context

    def post(self, request, **kwargs):
        user_membership = get_user_membership(request)
        user_subscription = get_user_subscription(request)
        # get value of the form input == selected membership
        selected_membership_type = request.POST.get('membership_type')

        selected_membership_qs = Membership.objects.filter(
            membership_type=selected_membership_type)
        print(selected_membership_qs)
        selected_membership = selected_membership_qs.first()
        print(selected_membership)
        # prepare subscription error message
        if user_membership.membership == selected_membership:
            if user_subscription is None:
                messages.info(request, "You already have this membership. Your \
					next payment is due {}".format('get this value from stripe'))
                # redirects user back to the url they came from
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        # assign to the session
        # Membership field
        request.session['selected_membership_type'] = selected_membership.membership_type

        return HttpResponseRedirect(reverse('memberships:payment'))


def PaymentView(request):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership(request)
    # get stripe API key from settings to pass into context so
    # that we can use it in the form
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    """
    On purchase
    """
    if request.method == "POST":
        try:
            token = request.POST['stripeToken']
            subscription = stripe.Subscription.create(
                customer=user_membership.stripe_customer_id,  # id on User Membership Model
                items=[
                    {   # Free, Pro, Enterprise
                        "plan": selected_membership.stripe_plan_id,
                    },
                ], # sets free trial instead of payment
                trial_period_days=100
            )

            return redirect(reverse('memberships:update-transactions',
                                    kwargs={
                                        'subscription_id': subscription.id
                                    }))

        except stripe.error.CardError as e:
            messages.info(request, "Your card has been declined")

    context = {
        'publishKey': publishKey,
        'selected_membership': selected_membership
    }

    return render(request, "memberships/membership_payment.html", context)


def updateTransactionRecords(request, subscription_id):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership(request)

    user_membership.membership = selected_membership
    user_membership.save()

    sub, created = Subscription.objects.get_or_create(
        user_membership=user_membership)
    sub.stripe_subscription_id = subscription_id
    sub.active = True
    sub.save()

    try:
        del request.session['selected_membership_type']
    except:
        pass

    messages.info(request, 'Successfully created {} membership'.format(
        selected_membership))
    return redirect('/memberships')


def cancelSubscription(request):
    user_sub = get_user_subscription(request)

    if user_sub.active is False:
        messages.info(request, "You dont have an active membership")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
    sub.delete()

    user_sub.active = False
    user_sub.save()

    free_membership = Membership.objects.filter(membership_type='Free').first()
    user_membership = get_user_membership(request)
    user_membership.membership = free_membership
    user_membership.save()

    messages.info(
        request, "Successfully cancelled membership. We have sent an email")
    # sending an email here

    return redirect('/memberships')


@login_required
def send_friend_request(request, id):
    # import pdb; pdb.set_trace()
    user = get_object_or_404(User, id=id)
    frequest, created = FriendRequest.objects.get_or_create(
    # returns object and bool T/F ^^
        from_user=request.user, # requesting user
		to_user=user) # receiving user
    return HttpResponseRedirect(user.membership.get_absolute_url())

@login_required
def cancel_friend_request(request, id):
		user = get_object_or_404(User, id=id)
		frequest = FriendRequest.objects.filter(
			from_user=request.user,
			to_user=user).first()
		frequest.delete()
		return HttpResponseRedirect(user.membership.get_absolute_url())

def accept_friend_request(request, id):
    # import pdb; pdb.set_trace();
    from_user = get_object_or_404(User, id=id)
    frequest = FriendRequest.objects.filter(from_user=from_user, to_user=request.user).first()
    user1 = frequest.to_user
    user2 = from_user

    user1.membership.friends.add(user2.membership)
    user2.membership.friends.add(user1.membership)
 # ^^membership is related name on user from usermembership model
    frequest.delete()
    return HttpResponseRedirect('/memberships/my_membership')


def delete_friend_request(request, id):
    from_user = get_object_or_404(User, id=id)
    frequest = FriendRequest.objects.filter(from_user=from_user, to_user=request.user).first()
    frequest.delete()
    return HttpResponseRedirect('/memberships/{}'.format(request.user.membership.slug))
    # return HttpResponseRedirect(reverse('profile-view', kwargs={'slug': request.user.profile.slug}))

def delete_friend(request, id):
    # import pdb; pdb.set_trace()
    user = UserMembership.objects.filter(user=request.user)[0]
    user.friends.get(id=id).usermembership_set.clear()
    return HttpResponseRedirect('/memberships/my_membership')


def profile_view(request, slug):
    p = UserMembership.objects.filter(slug=slug).first()
    # get_object_or_404
    u = p.user
    current_user = UserMembership.objects.filter(user=request.user)[0]
    user_membership = UserMembership.objects.filter(slug=slug).first()
    sent_friend_requests = FriendRequest.objects.filter(from_user=p.user)
    rec_friend_requests = FriendRequest.objects.filter(to_user=p.user)

    friends = p.friends.all()

    # import pdb; pdb.set_trace()

videoservice/memberships/templates/memberships/base.html
{% load static %} <!DOCTYPE html>
<html lang="en">
  <head>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/userprofile.css' %}"
    />

    <title>The Spectrum</title>
  </head>
  <body>
    {% include 'courses/navbar.html' %} {% include 'courses/messages.html' %} {%
    if not request.user.is_authenticated %}
    <div class="container">
      <nav class="breadcrumb">
        <ol class="breadcrumb">
          <li class="pull-left">
            <a href="{% url 'memberships:signup' %}">Register</a>
          </li>
          <li class="pull-right">
            <a href="{% url 'memberships:login' %}">Login</a>
          </li>
          <li class="pull-right"><a href="/memberships">Memberships</a></li>
        </ol>
      </nav>
    </div>
    {% else %}
    <div class="container">
      <ol class="breadcrumb">
        <li><a href="/courses">Courses</a></li>
        <li><a href="/blog">Blog</a></li>
        <li>
          <a href="/memberships/my_membership/">View Membership Details</a>
        </li>
        {% block post_detail_link %} {% endblock %}
        <li class="pull-right">
          <a href="{% url 'memberships:logout' %}">Logout</a>
        </li>
        <li class="pull-right"><a href="/memberships">Memberships</a></li>
      </ol>
    </div>
    {% endif %}
    <div class="container-fluid">{% block content%} {% endblock content%}</div>

    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous"
    ></script>
    <script>
      $("#relationship").text("");
    </script>
  </body>
</html>

videoservice/memberships/templates/memberships/login.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
        <title>The School of Code</title>
  </head>
  <body>

<div class="container">
    <div class="row">
        <div class="logo">

        </div>
        <div class="login">
            <ul class="tab-group">
             <li class="tab"><a href="{% url 'memberships:signup' %}"><strong>sign up</strong></a></li>
             <li class="tab active"><a href="{% url 'memberships:login' %}"><strong>log in</strong></a></li>
            </ul>
            <form id="login_form" method="post" action="{% url 'memberships:login' %}">
                    {% csrf_token %}
                    <label class="label">Username</label> <input type="text" name="username" value="" size="50" required="required"/>
                    <label class="label">Password</label><input type="password" name="password" value="" size="50" required="required" />
                       <input type="submit" value="submit" class="btn btn-primary btn-block btn-large"/>
            </form>
        </div>
    </div>
</div>



    </body>
</html>

videoservice/memberships/templates/memberships/membership_list.html
{% extends 'memberships/base.html' %}


{% block content %}

<hr class="short"/>

<!-- BENEFITS FOR ALL MEMBERHSIP LEVELS -->
<h2 class="benefits-title" align="center">Benefits for All Membership Levels</h2>
<div class="container">
		<div class="row benefits">
				<div class="six columns benefits-1">
						 <ul class="benefits-ul-1">
								<li class="check">
										<i class="fas fa-check"></i>
									Personalized membership cards
								</li>
								<li class="check">
										<i class="fas fa-check"></i>
									Unlimited View Time
								</li>
								<li class="check">
										<i class="fas fa-check"></i>
									Instant Chat
								</li>
								<li class="check">
										<i class="fas fa-check"></i>
									Communicate with other Users
								</li>
								<li class="check">
										<i class="fas fa-check"></i>
									10 percent discount in our &amp; store
								</li>
					 </ul>
				</div>
				<div class="six columns benefits-2 omega">
						<ul class="benefits-ul-2">
							 <li class="check">
									<i class="fas fa-check"></i>
								 <a href="#">
									 Discounts on global confrences
									</a> and special events</li>
								<li class="check">
										<i class="fas fa-check"></i>
									Previews of special lessons
								</li>
								<li class="check">
										<i class="fas fa-check"></i>
									Exclusive e-mail announcements
								</li>
							 <li class="check">
									<i class="fas fa-check"></i>
							  Free subscription to our member magazine,
							 <em>Shorelines</em>
							</li>
					 </ul>
				</div>
		 </div>
</div>


<div class="container">
	<div class="row">
		{% for object in object_list %}
			<div class="col-sm-4 col-md-4">
			   <div class="price-table">
					<div class="price-head">
						<h4>{{ object.membership_type }}</h4>
					</div>
					<div class="price-content">
					  <h5 class="price-title">Price: {{ object.price }}<small>Monthly</small></h5>
					  <h5>Included Courses</h5>
					  <ul>
							{% for course in object.course_set.all %}

							<li class="card-text">{{ course.title }}</li>
							{% endfor %}
					  </ul>
					<div class="price-button">
					  {% if object.membership_type != 'Free' %}
			<form method="POST" action="{% url 'memberships:select' %}">
				{% csrf_token %}
				{% if object.membership_type != current_membership %}
					<button>Select</button>
				{% else %}
					<p class="status">This is your current membership</small>
				{% endif %}
				<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
			</form>
			{% endif %}
					  </div>
					</div>
				  </div>
				</div>
			{% endfor %}
	</div>
</div>



{% endblock content %}

videoservice/memberships/templates/memberships/profile-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/userprofile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <title>Membership</title>
</head>
<body>
    {% include 'courses/navbar.html' %}
    {% include 'courses/messages.html' %}
    {% if not request.user.is_authenticated %}
    <div class="container">
     <nav class="breadcrumb">
            <ol class='breadcrumb'>
                <li class='pull-left'><a href="{% url 'memberships:register' %}">Register</a></li>
                <li class='pull-right'><a href="{% url 'memberships:login' %}">Login</a></li>
                <li class='pull-right'><a href='/memberships'>Memberships</a></li>
            </ol>
     </nav>
    </div>
    {% else %}
    <div class="container">
            <ol class='breadcrumb'>
                <li><a href='/courses'>Courses</a></li>
                <li><a href='/blog'>Blog</a></li>
                <li><a href='/memberships/my_membership/'>View Membership Details</a></li>
                    {% block post_detail_link %}
                    {% endblock %}
                <li class='pull-right'><a href="{% url 'memberships:logout' %}">Logout</a></li>
                <li class='pull-right'><a href='/memberships'>Memberships</a></li>
            </ol>
        </div>
    {% endif %}
    <div class="container-fluid">
            {% block profile %}

            {% endblock %}
    </div>

    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
<script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>
</body>
</html>

videoservice/memberships/templates/memberships/profile_view.html
{% extends 'memberships/base.html' %}

{% block content %}

	<div class="container text-center">



        <div id="home" class="tab-pane in active">
				<div class="row">
					<div class="col-xs-12 col-sm-3 center">
						{% if not user_membership.avatar %}

						<span class="profile-picture">
								<img class="editable img-responsive" alt=" Avatar" id="avatar2" src="http://bootdey.com/img/Content/avatar/avatar6.png">
						</span>
						{% else %}
						<span class="profile-picture">
								<img class="editable img-responsive" alt=" Avatar" id="avatar2" src="{{ user_membership.avatar.url }}">
							</span>
						{% endif %}

						<div class="space space-4"></div>
						{% if current_user in friends %}
						<h1>Already Friends</h1>
						{% else %}
							{% if button_status == 'not_friend' %}
								<small>
									<a class='btn btn-sm btn-block btn-success' href="/memberships/friend-request/send/{{ u.id }}">
										<i class="ace-icon fa fa-plus-circle bigger-120"></i>
										<span class="bigger-110">Add as a friend</span>
									</a>
								</small>

							{% elif button_status == 'friend_request_sent' %}
								<small>
									<a class="btn btn-sm btn-block btn-warning" href="/memberships/friend-request/cancel/{{ u.id }}">
										<i class="ace-icon fas fa-ban bigger-120"></i>
										<span class="bigger-110">Cancel Request</span>
									</a>
								</small>
							{% endif %}
						{% endif %}




						<a href="#" class="btn btn-sm btn-block btn-primary">
							<i class="ace-icon fa fa-envelope-o bigger-110"></i>
							<span class="bigger-110">Send a message</span>
						</a>

					</div><!-- /.col -->

					<div class="col-xs-12 col-sm-9">
						<h4 class="blue">
							<span class="user-profile-name middle">{{ user_membership.first_name }} {{ user_membership.last_name }}</span>
							<hr>

						</h4>

						<div class="profile-user-info">
							<div class="profile-info-row">
								<div class="profile-info-name"><strong>UserName</strong></div>

								<div class="profile-info-value">
									<span>{{ u.username }}</span>
								</div>
							</div>

							<div class="profile-info-row">
								<div class="profile-info-name"><strong>Location</strong> </div>

								<div class="profile-info-value">
									<i class="fa fa-map-marker light-red bigger-110"></i>
									<span>{{ user_membership.location }}</span>
								</div>
							</div>

							<div class="profile-info-row">
								<div class="profile-info-name"><strong>Birth Date</strong></div>

								<div class="profile-info-value">
									<span>{{ user_membership.birth_date }}</span>
								</div>
							</div>

							<div class="profile-info-row">
								<div class="profile-info-name"><strong>Joined</strong></div>

								<div class="profile-info-value">
									<span>{{ user_membership.user_subscription.get_created_date }}</span>
								</div>
							</div>
							{% if user_subscription != None %}
							<div class="profile-info-row">
								<div class="profile-info-name"> Membership Type </div>

								<div class="profile-info-value">
									<span>{{ user_membership.membership.membership_type }}</span>
								</div>
							</div>
							{% endif %}
						</div>

						<div class="hr hr-8 dotted"></div>

						<div class="profile-user-info">


							<div class="profile-info-row">
									<div class="profile-info-name">
                                            <i class="fab fa-facebook"></i>
									</div>

									<div class="profile-info-value">

										<a href="#">Find me on Facebook</a>
									</div>
								</div>
						</div>

{% endblock %}

videoservice/memberships/templates/memberships/register.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
        <title>The School of Code</title>
    </head>

    <body>
        <h4 class="info">Become a member and start learning today</h4>

        {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="{% url 'memberships:memberships' %}">Check out our available memberships</a><br />
        {% else %}

        <div class="container">
                <div class="row">
                    <div class="logo">

                    </div>
                    <div class="login">
                        <ul class="tab-group">
                         <li class="tab active"><a href="{% url 'memberships:signup' %}"><strong>sign up</strong></a></li>
                         <li class="tab"><a href="{% url 'memberships:login' %}"><strong>log in</strong></a></li>
                        </ul>

<form id="user_form" method="post" action="{% url 'memberships:signup' %}"
      enctype="multipart/form-data">

            {% csrf_token %}
            <label class="label">First Name</label> <input type="text" name="first_name" value="" size="50" required="required"/>
            <label class="label">Last Name</label> <input type="text" name="last_name" value="" size="50" required="required"/>
            <label class="label">Email</label> <input type="email" name="email" value="" size="50" required="required"/>
            <label class="label">Username</label> <input type="text" name="username" value="" size="50" required="required"/>
            <label class="label">Password</label><input type="password" name="password" value="" size="50" required="required" />
            <input type="submit" value="Register" class="btn btn-primary btn-block btn-large"/>

</form>

                    </div>
                </div>
            </div>


        {% endif %}
    </body>
</html>