videoservice/blog/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (
    posts_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    PostLikeToggle,
    PostLikeAPIToggle,
    newsletter_signup,
    newsletter_unsubscribe,
    search_list_view,
)



app_name = 'blog'


urlpatterns = [
    url(r'^$', posts_list, name='blog'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like'),
    url(r'^api/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like_api'),
    url(r'sign_up/$', newsletter_signup, name='newsletter_signup'),
    url(r'unsubscribe/$', newsletter_unsubscribe, name='newsletter_unsubscribe'),
    url(r'^searchlist$', search_list_view, name='search_list'),
]

videoservice/courses/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, LessonDetailView

app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<slug>', CourseDetailView.as_view(), name='detail'),
    path('<course_slug>/<lesson_slug>',
         LessonDetailView.as_view(), name='lesson-detail'),
]

videoservice/memberships/urls.py
from django.urls import path
from django.conf.urls import url
from allauth.account.views import LoginView, SignupView
from .views import (
	MembershipSelectView,
	PaymentView,
	updateTransactionRecords,
	my_membership_view,
	cancelSubscription,
	user_logout_view,
	profile_view,
	accept_friend_request,
	send_friend_request,
	delete_friend_request,
	cancel_friend_request,
	delete_friend,
	)

app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
	path('signup/', SignupView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', user_logout_view, name='logout'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransactionRecords, name='update-transactions'),
	path('my_membership/', my_membership_view, name='my_membership'),
	path('cancel/', cancelSubscription, name='cancel'),
	url(r'^(?P<slug>[\w-]+)/$', profile_view, name='profile-view'),
	url(r'^friend-request/send/(?P<id>[\w-]+)/$', send_friend_request),
    url(r'^friend-request/cancel/(?P<id>[\w-]+)/$', cancel_friend_request),
    url(r'^friend-request/accept/(?P<id>[\w-]+)/$', accept_friend_request),
    url(r'^friend-request/delete/(?P<id>[\w-]+)/$', delete_friend_request),
	url(r'^friends/delete/(?P<id>[\w-]+)/$', delete_friend),
]

videoservice/blog/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.contenttypes.models import ContentType
from comments.models import Comment
from memberships.models import UserMembership
import datetime


class Post(models.Model):
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length= 50)
    description = models.TextField(max_length=1000)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    author = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_image', null=True, blank=True)
    likes = models.ManyToManyField(UserMembership, blank=True, related_name='post_likes')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={ "slug": self.slug })

    def get_update_url(self):
        return reverse('blog:update', kwargs={ "slug": self.slug })

    def get_delete_url(self):
        return reverse('blog:delete', kwargs={ "slug": self.slug })

    def get_like_url(self):
        return reverse('blog:like', kwargs={ "slug": self.slug })

    def get_api_like_url(self):
        return reverse('blog:like_api', kwargs={ "slug": self.slug })

    class Meta:
            db_table = 'Post'

    @property # took out of views and set as prop. on model
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property # gets model type for comments genericforeignkey
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


# auto generates slug for each post that was created
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_reciever(sender, instance, *args, **kwargs):
    slug = slugify(instance.title)
    exists = Post.objects.filter(slug=slug).exists()
    if exists:
        slug = "%s-%s" %(slug, instance.id)
    instance.slug = slug

pre_save.connect(pre_save_post_reciever, sender=Post)


class NewsLetterUser(models.Model):
    email = models.EmailField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

videoservice/blog/forms.py
from django.contrib.auth.models import User
from django import forms
from pagedown.widgets import PagedownWidget
from memberships.models import UserMembership
from .models import Post, NewsLetterUser
from crispy_forms.helper import FormHelper


class PostModelForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs = {
            'class': 'form-control'
        }
    ))
    description = forms.CharField(widget=PagedownWidget)

    class Meta:
        model = Post
        fields = ('title', 'description', 'image')


class SearchForm(forms.ModelForm):

    class Meta:
        model = UserMembership
        fields = ('user',)

    def __init__(self, search_term, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['search'].queryset = UserMembership.objects.filter(exclude=request.user)


class NewsLetterSignUpForm(forms.ModelForm):

    class Meta:
        model = NewsLetterUser
        fields = ('email',)

        def clean_email(self):
            email = self.cleaned_data.get('email')
            return email

videoservice/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import logout, login, authenticate
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView, ListView
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext

from .models import Post
from memberships.models import UserMembership
from memberships.views import get_user_membership
from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostModelForm, NewsLetterSignUpForm


def search_list_view(request):
    search_query = request.GET.get('search')
    search_results = UserMembership.objects.filter(user__username__icontains=search_query)

    return render(request, 'blog/posts_list.html', {'search_results': search_results})

"""
- Query all posts ordered by reversing the order of the timestamp
so most recent posts show up first.
- Query all posts to be filtered by title using Django's search tool
- Using Paginator, create a new page for every 3 posts.
- For recent posts, show 3 most recent
"""
def posts_list(request):
    queryset_list = Post.objects.all().order_by("-timestamp")
    users = UserMembership.objects.exclude(user=request.user)
    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query)
            ).distinct()
    paginator = Paginator(queryset_list, 3)
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    # get the last 3 posts
    recent_posts = Post.objects.order_by('-timestamp')[0:3]

    context = {
        'users': users,
        'all_posts': queryset,
        'page_request_var': page_request_var,
        'recent_posts': recent_posts
    }
    return render(request, 'blog/posts_list.html', context)

"""
Get the user and the specific post by slug.
Initialize comments object by "post" content type and the ID
Pass in form with the initial data
Execute comment form and clean data
Determine comments parent child relation
Create comment
"""
def post_detail(request, slug=None):
    user = UserMembership.objects.filter(user=request.user)[0]
    instance = get_object_or_404(Post, slug=slug)
    # ContentType.objects.get_for_model(Post)
    # obj_id = instance_id
    # comments = Comments.objects.filter(content_type=content_type, object_id=obj_id)
    initial_data = {
        "content_type": instance.get_content_type, # Property on Model
        "object_id": instance.id # POST OBJECT ID
    }
    print(initial_data)
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type) # gets from model class
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try: # make sure parent_id exists in DB
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None # parent is None by default

        if parent_id: # does parent QS exist?
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user = request.user,
            content_type = content_type,
            object_id = obj_id,
            content = content_data,
            parent = parent_obj,
        )
        # re render post detail page after comment
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = instance.comments # property on Post Model
    context = {
        'auth_user': user,
        'instance': instance,
        'comments': comments,
        'comment_form': form,
    }
    return render(request, 'blog/posts_detail.html', context)


class PostLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Post, slug=slug)
        url_ = obj.get_absolute_url()
        user = obj.author
        if user:
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_


class PostLikeAPIToggle(APIView):
    """
    View to list all users in the system.

    * Requires token authentication.
    * Only admin users are able to access this view.
    """
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, slug=None, format=None):
        # slug = self.kwargs.get('slug')
        obj = get_object_or_404(Post, slug=slug)
        url_ = obj.get_absolute_url()
        user = get_user_membership(request)
        updated = False
        liked = False
        if user.user.is_authenticated:
            if user in obj.likes.all():
                liked = False
                updated = True
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)
                updated = True
        data = {
            "updated": updated,
            "liked": liked
        }

        return Response(data)

"""
Allows a user to create a post. Connects user/user membership to
author of a blog post.
"""
@login_required
def post_create(request):
    form = PostModelForm()
    if request.POST:
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = get_user_membership(request)
            form.instance.save()
        post = get_object_or_404(Post, slug=form.instance.slug)
        return redirect(post.get_absolute_url())

    context = {'form': form}
    return render(request, "blog/create_post.html", context)



def post_update(request, slug):
	unique_post = get_object_or_404(Post, slug=slug)
	form = PostModelForm(request.POST or None,
						request.FILES or None,
						instance=unique_post)
	if form.is_valid():
		form.save()
		return redirect('/blog/')

	context = {
		'form': form
	}
	return render(request, "blog/create_post.html", context)


def post_delete(request, slug):
    unique_post = get_object_or_404(Post, slug=slug)
    unique_post.delete()
    return redirect('blog:blog')


def newsletter_signup(request):
    if request.method == 'POST':
        form = NewsLetterSignUpForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            if NewsLetterUser.objects.filter(email=instance.email).exists():
                messages.warning(request, 'Your email already exists.')
            else:
                instance.save()
    else:

        form = NewsLetterSignUpForm()

        return render(request, 'blog/posts_list.html', {'form': form})

def newsletter_unsubscribe(request):
    form = NewsLetterSignUpForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        if NewsLetterUser.objects.filter(email=instance.email).exists():
            NewsLetterUser.objects.filter(email.instance.email).delete()
        else:
            print('Sorry, we did not find your email address.')

        context = {
            'form': form
        }
        template = 'blog/unsubscribe.html'
        return render(request, template, context)

videoservice/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c|Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <title>The Short Stack</title>
{% block head_extra %}

{% endblock %}
</head>

<body>
    <div id="fb-root"></div>
    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
{% include 'blog/navbar.html' %}
{% include 'courses/messages.html' %}

{% if not request.user.is_authenticated %}

    <div class="container">
        <nav class="breadcrumb">
            <ol class='breadcrumb'>
                <li class='pull-left'>
                    <a href="{% url 'memberships:signup' %}">Register</a>
                </li>
                <li class='pull-right'>
                    <a href="{% url 'memberships:login' %}">Login</a>
                </li>
                <li class='pull-right'>
                    <a href='/memberships'>Memberships</a>
                </li>
            </ol>
        </nav>
    </div>


    {% else %}

    <div class="container">
        <ol class='breadcrumb'>
            <li>
                <a href='/courses'>Courses</a>
            </li>
            <li>
                <a href='/blog'>Blog</a>
            </li>
            <li>
                <a href='/memberships/my_membership/'>View Membership Details</a>
            </li>
            {% block post_detail_link %} {% endblock %}
            <li class='pull-right'>
                <a href="{% url 'memberships:logout' %}">Logout</a>
            </li>
            <li class='pull-right'>
                <a href='/memberships'>Memberships</a>
            </li>
        </ol>
    </div>

    {% endif %}

    <div class="container-fluid">
        {% block content%} {% endblock content%}
    </div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.5.0/marked.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

<script>
            $(document).ready(function(){
                function updateText(btn, newCount, verb) {
                    btn.text(newCount + "" + verb)
                    btn.attr("data-likes", newCount)
                }

                $(".like-btn").click(function (e) {
                    e.preventDefault()
                    const this_ = $(this)
                    const likeUrl = this_.attr("data-href")
                    const likeCount = parseInt(this_.attr("data-likes")) | 0
                    const addLike = likeCount + 1
                    const removeLike = likeCount - 1
                    if (likeUrl){
                        $.ajax({
                            url: likeUrl,
                            method: "GET",
                            data: {},
                            success: function (data) {
                                console.log(data)
                                var newLikes;
                                if (data.liked) {
                                    updateText(this_, addLike, "unlike")
                                } else {
                                    updateText(this_, removeLike, "like")
                                }
                            }, errors: function (error) {
                                console.log(error)
                                console.log("error")
                            }
                     })
                 }
            })
        })
</script>
<script>
    $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text()
            console.log(content)
            var markedContent = marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
        })
    })
</script>
<script>
    $(document).ready(function(){
        $('.comment-reply-btn').click(function(event){
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle();
        })
    })
</script>

</body>

</html>

videoservice/blog/templates/blog/confirm_delete.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
  <h1>Confirm Delete</h1>


            <form method="POST" action="."> {% csrf_token %}
                <p>A re you sure you want to delete: "{{ object.content }}"?</p>

                <input type='submit' value='Confirm' class='btn btn-warning'>
                <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
            </form>
        </div>



        <hr/>
</div>


{% endblock content %}

videoservice/blog/templates/blog/navbar.html
{% load static %}
<div class="container-fluid">
    <div class="top-nav">
     <div class="col-sm-2 col-md-2 col-lg-2">
         <img class="logo" src="https://s15.postimg.cc/dgcqp5jln/spectrum.png">
     </div>
     <div class="col-sm-4 col-md-4 col-lg-4">
         <a href="{% url 'home' %}">
            <i class="nav-icon fas fa-home fa-3x"></i>
        </a>
                    <a href="{% url 'courses:list' %}">
                        <i class="nav-icon fas fa-video fa-3x">
                        </i>
                    </a>
                    <a href="{% url 'blog:blog' %}">
                        <i class="nav-icon fab fa-stack-exchange fa-3x">
                        </i>
                    </a>
                </div>

                <div class="col-md-6 nav-auth">
                    <div id="nav-auth-wrap">
                      <div>
                          <h4 class="hello">Hello, {{ user.membership.first_name }}</h4>
                      </div>
                      <div>
                          {% if user.membership.avatar %}
                          <a href="/memberships/my_membership">
                            <img class="nav-user-av" src="{{ user.membership.avatar.url}}">
                          </a>
                          {% else %}
                          <a href="/memberships/my_membership">
                            <img class="nav-user-av" src="http://bootdey.com/img/Content/avatar/avatar6.png">
                          </a>
                          {% endif %}
                      </div>
                      <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                         <i class="fas fa-cog nav-settings fa-2x"></i>
                        </a>
                         <ul class="dropdown-menu">
                            <li class="nav-drop-i"><a href="/contact/">Contact</a></li>
                            <li class="nav-drop-i"><a href="{% url 'memberships:logout' %}">Logout</a></li>
                         </ul>
                      </div>
                     </div>
                </div>
    </div>
</div>

videoservice/blog/templates/blog/posts_list.html
{% extends 'blog/base.html' %}



{% block content %}
{% if not request.user.is_authenticated %}
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <div class="non-member-card">
        <div class="card-block">
          <h4 class="non-member-card-title">You are not yet a member</h4>
          <p class="non-member-card-text">The reason why you do not have access to
            this page is because you are not registered as a member.
            Please click below to register.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
        <button type="button" class="btn btn-success">Sign Up</button>
      </div>
    </div>

    {% else %}

    <div class="container">

      <div class="row col-xs-12 col-md-12 col-lg-12">
        <div class="short-stack">
          <h1 class="ss-title">Spectrum Presents</h1>
          <h2 class="ss-subtitle">The Short Stack</h2>
        </div>
      </div>
    </div>

    <br>

    <div class="container-fluid">
      <div class="row">
        <aside class="col-md-3">
          <div class="blog-users">

            <header>
              Users
            </header>

            <form action="{% url 'blog:search_list' %}"class="cont">
              <input type="search" class="srchFld" name="search" placeholder="" ng-model="search"/>
              <button type="submit" class="srchBtn">Search</button>
              <div class="entypo-search ico"></div>
            </form>
            {% for user in search_results %}

            <a href="{{ user.get_absolute_url }}">
              <span class="imgWrpr">
                {% if user.avatar %}
                <img class="user-avatar" src="{{ user.avatar.url }}">
                {% else %}
                <img class="user-avatar" src="http://bootdey.com/img/Content/avatar/avatar6.png">
                {% endif %}
              </span>
              <span class="contactInfo">{{ user }}</span>
            </div>
          </a>

          {% endfor %}

          {% for user in users %}
          <div class="wrapr row">
            <a href="{{ user.get_absolute_url }}">
              <span class="imgWrpr">
                {% if user.avatar %}
                <img class="user-avatar" src="{{ user.avatar.url }}">
                {% else %}
                <img class="user-avatar" src="http://bootdey.com/img/Content/avatar/avatar6.png">
                {% endif %}
              </span>
              <span class="contactInfo">{{ user }}</span>
            </div>
          </a>
          {% endfor %}
        </div>
      </aside>


      <div class="col-sm-6 col-md-6">
        <div class="search-box">
          <form class="search-form" action="/blog/" method="get">
            <input class="form-control" value="{{ request.GET.q }}" name="q" size="40" type="text" placeholder="Search Posts"/>
            <button type="submit" class='btn btn-link search-btn'>
              <i class='glyphicon glyphicon-search'></i>
            </button>

          </form>
        </div>
      </div>
      <div class="col-md-6">

        {% for post in all_posts %}

        {% if post.image %}
        <article class="box">
          <header class="post-header">
            <div class="meta">
              <div class="row inline">
                <div class="col-md-2">
                  <a href="{{ post.author.get_absolute_url }}">
                    <img height="80" width="80" id="avatar" class="img-responsive img-circle" src="{{ post.author.avatar.url }}"
                    alt='author-avatar' />
                  </a>
                </div>
                <div class="post-author">
                  <strong id="label">
                    <span class="author">{{ post.author.user.username }}</span>
                  </strong>
                </div>
                <span class="date"><strong><em>Created:</em>{{ post.timestamp }}</strong></span>
              </div>
            </div>
          </header>
          <div class="entry-content">

            <h2 class="text-center blog-title">{{ post.title }}</h2>

            <img class="img-responsive img-circle image-detail" src="{{ post.image.url }}"
            height="250" width="250" alt='post-image' />

            <p class="content-markdown">{{ post.description|safe|truncatechars:300}}&hellip;</p>
          </div>
          <footer class="post-footer">
            <div class="row">
              <a href="{{ post.get_like_url }}" data-likes="{{ post.likes.count }}" class="like-btn btn btn-success"
              data-href="{{ post.get_api_like_url }}">
              Like
              <span>{{ post.likes.count }}</span>
            </a>
            <a href="{{ post.get_absolute_url }}" class="post-btn pull-right">Read More
              <span class="glyphicon glyphicon glyphicon-chevron-right" aria-hidden="true">
              </span>
            </a>
          </div>
        </footer>
      </article>

      {% else %}

      <article class="box">
        <header class="post-header">
          <div class="meta">
            <div class="row inline">
              <div class="col-md-2">
                <a href="{{ post.author.get_absolute_url }}">
                  <img height="80" width="80" id="avatar" class="img-responsive img-circle" src="{{ post.author.avatar.url }}"
                  alt='author-avatar' />
                </a>
              </div>
              <div class="post-author">
                <strong id="label">
                  <span class="author">{{ post.author.user.username }}</span>
                </strong>
              </div>
              <span class="date"><strong><em>Created:</em>{{ post.timestamp }}</strong></span>
            </div>
          </div>
        </header>
        <div class="entry-content">

          <h2 class="text-center blog-title">{{ post.title }}</h2>


          <p class="content-markdown content-descr">{{ post.description|safe|truncatechars:300 }}&hellip;</p>
        </div>
        <footer class="post-footer">
          <a href="{{ post.get_like_url }}" data-likes="{{ post.likes.count }}" class="like-btn btn btn-success"
          data-href="{{ post.get_api_like_url }}">
          Like
          <span>{{ post.likes.count }}</span>
        </a>
        <a href="{{ post.get_absolute_url }}" class="post-btn">Read More
          <span class="glyphicon glyphicon glyphicon-chevron-right" aria-hidden="true">
          </span>
        </a>
      </footer>
    </article>

    {% endif %}

    {% endfor %}

    <ul class="pagination modal-1">
      <span class="step-links">
        {% if all_posts.has_previous %}
        <li>
          <a class="prev" href="?{{ page_request_var }}={{ all_posts.previous_page_number }}">previous</a>
        </li>
        {% endif %}
        <!-- <span class="current active">
          Page {{ all_posts.number }} of {{ all_posts.paginator.num_pages }}.
        </span> -->
        {% if all_posts.has_next %}
        <li>

        </li>
        <a class="next" href="?{{ page_request_var }}={{ all_posts.next_page_number }}">Next &raquo;</a>
        {% endif %}
      </span>
    </ul>

  </div>
  <a href="/blog/create/" class="gradient-btn" data-title="Create Post"></a>
  <aside class="col-sm-12 col-md-2 col-lg-2">
    <div class="mb-3">
      <div class="sidebar widget">
        <h3>Recent Post</h3>
        <ul>
          {% for obj in recent_posts %}
          <li>
            <div class="sidebar-thumb">
                                    <img class="animated rollIn" src="{{ obj.author.avatar.url }}" alt="" />
                                </div><!-- .Sidebar-thumb -->
                                <div class="sidebar-content">
                                    <h5 class="animated bounceInRight"><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h5>
                                </div><!-- .Sidebar-thumb -->
                                <div class="sidebar-meta">
                                    <span class="time" ><i class="fa fa-clock-o"></i> {{ obj.timestamp }}</span>
                                    <span class="comment"><i class="fa fa-comment"></i> {{ obj.comments.count }} Comments</span>
                                </div><!-- .Sidebar-meta ends here -->
                            </li><!-- .Li ends here -->
                            {% endfor %}
                          </ul><!-- .Ul ends here -->
                      </div><!-- .Widget ends here -->
      </div>
      </aside>


    </div>
  </div>


  {% endif %}

  {% endblock %}