videoservice/blog/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (
    posts_list,
    post_detail,
    post_create,
    post_update,
    post_delete,
    PostLikeToggle,
    PostLikeAPIToggle,
    newsletter_signup,
    newsletter_unsubscribe,
    search_list_view,
)



app_name = 'blog'


urlpatterns = [
    url(r'^$', posts_list, name='blog'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like'),
    url(r'^api/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like_api'),
    url(r'sign_up/$', newsletter_signup, name='newsletter_signup'),
    url(r'unsubscribe/$', newsletter_unsubscribe, name='newsletter_unsubscribe'),
    url(r'^searchlist$', search_list_view, name='search_list'),
]

videoservice/courses/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, LessonDetailView

app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<slug>', CourseDetailView.as_view(), name='detail'),
    path('<course_slug>/<lesson_slug>',
         LessonDetailView.as_view(), name='lesson-detail'),
]

videoservice/memberships/urls.py
from django.urls import path
from django.conf.urls import url
from allauth.account.views import LoginView, SignupView
from .views import (
	MembershipSelectView,
	PaymentView,
	updateTransactionRecords,
	my_membership_view,
	cancelSubscription,
	user_logout_view,
	profile_view,
	accept_friend_request,
	send_friend_request,
	delete_friend_request,
	cancel_friend_request,
	delete_friend,
	)

app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
	path('signup/', SignupView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', user_logout_view, name='logout'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/', updateTransactionRecords, name='update-transactions'),
	path('my_membership/', my_membership_view, name='my_membership'),
	path('cancel/', cancelSubscription, name='cancel'),
	url(r'^(?P<slug>[\w-]+)/$', profile_view, name='profile-view'),
	url(r'^friend-request/send/(?P<id>[\w-]+)/$', send_friend_request),
    url(r'^friend-request/cancel/(?P<id>[\w-]+)/$', cancel_friend_request),
    url(r'^friend-request/accept/(?P<id>[\w-]+)/$', accept_friend_request),
    url(r'^friend-request/delete/(?P<id>[\w-]+)/$', delete_friend_request),
	url(r'^friends/delete/(?P<id>[\w-]+)/$', delete_friend),
]

videoservice/courses/models.py
from django.db import models
from memberships.models import Membership
from django.urls import reverse


def get_membership_instance(type):
    qs = Membership.objects.filter(membership_type=type)
    if qs.exists():
        return qs[0]
    return None


class Course(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    description = models.TextField()
    image = models.ImageField(upload_to="course_img", null=True, blank=True)
    allowed_membership = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def lessons(self):  # grouping lessons with a course in a specific order
        return self.lesson_set.all().order_by('position')

    class Meta:
        db_table = 'Course'


class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    position = models.IntegerField()
    video_url = models.FileField(
        upload_to='videos/%Y/%m/$D/', null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail', kwargs={'course_slug': self.course.slug, 'lesson_slug': self.slug})

    class Meta:
        db_table = 'Lesson'

videoservice/courses/forms.py
from django import forms

from .models import Course, get_membership_instance


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['slug', 'title', 'description', 'image', 'allowed_membership']

    def clean(self, *args, **kwargs):
        form_data = self.cleaned_data
        free_mem = get_membership_instance('Free')
        ent_mem = get_membership_instance('Ent')

        # if the non-free memberships are allowed, add the free membership
        if form_data['allowed_membership'].count() >= 1:
            if free_mem not in form_data['allowed_membership'].all():
                raise forms.ValidationError(
                    "The Free membership should be allowed too!")

videoservice/courses/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View
from .models import Course, Lesson
from memberships.models import UserMembership, Membership


class CourseListView(ListView):
    model = Course


class CourseDetailView(DetailView):
    model = Course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lesson'] = Lesson.objects.all()
        return context



class LessonDetailView(View):
 # filter all the courses, and then filter that course's lessons for a specific lesson
 # ..yeah wtf
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):

        # create course qs and filter it by slug.
        course_queryset = Course.objects.filter(slug=course_slug)
        if course_queryset.exists():
            course = course_queryset.first()

        # grabs all lessons by course
        lesson_queryset = course.lessons.filter(slug=lesson_slug)
        if lesson_queryset.exists():
            lesson = lesson_queryset.first()

        user_membership = UserMembership.objects.filter(user=request.user).first()
        user_membership_type = user_membership.membership.membership_type #membership types
        # grab courses allowed by membership type
        course_allowed_mem_types = course.allowed_membership.all()
         # MAny to Many -allowed memberships

        context = {
            'object': None
        }

        # check to see lesson available for the user's membership type
        # how can i can i pass the membership choice with free included?
        if course_allowed_mem_types.filter(membership_type=user_membership_type).exists():
            context = {'object': lesson }


        return render(request, 'courses/lesson_detail.html', context)

videoservice/courses/templates/courses/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=PT+Sans|Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/courses.css' %}">
    <title>The Spectrum</title>
</head>
<body>
<div id="fb-root"></div>
<script>(function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.1';
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
</script>
    {% include 'courses/navbar.html' %}
    {% include 'courses/messages.html' %}
    {% if not request.user.is_authenticated %}
    <div class="container">
     <nav class="breadcrumb">
            <ol class='breadcrumb'>
                <li class='pull-left'><a href="{% url 'memberships:signup' %}">Register</a></li>
                <li class='pull-right'><a href="{% url 'memberships:login' %}">Login</a></li>
                <li class='pull-right'><a href='/memberships'>Memberships</a></li>
            </ol>
     </nav>
    </div>
    {% else %}

    <div class="container">
            <ol class='breadcrumb'>
                <li><a href='/courses'>Courses</a></li>
                <li><a href='/blog'>Blog</a></li>
                <li><a href='/memberships/my_membership/'>View Membership Details</a></li>
                    {% block post_detail_link %}
                    {% endblock %}
                <li class='pull-right'><a href="{% url 'memberships:logout' %}">Logout</a></li>
                <li class='pull-right'><a href='/memberships'>Memberships</a></li>
            </ol>
        </div>
    {% endif %}
    <div class="container-fluid">

            {% block content%}

            {% endblock %}

    </div>

    <script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ticker.js' %}"></script>

</body>
</html>

videoservice/courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}

{% block content %}

<article class="lesson-content">
    {% for lesson in object.lessons %}

    <div class="panel lesson">
    <a href="{{ lesson.get_absolute_url }}">
        <img class="panel-img" src="{{ lesson.thumbnail.url }}">
        <span class="panel-tab"><p>{{ lesson.title }}</p></span>
    </a>


    </div>

    {% endfor %}

</article>

{% endblock content%}

videoservice/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}



{% block content %}

<hr>
    <div class="vault-items-container">
                {% for object in object_list %}

            <div class="vault-item password-item" tabindex="0">
                <div class="vault-item-thumbnail">
                     <img class="course-img img-responsive img-rounded" src="{{ object.image.url }}" alt=""  />
                    </div>
                <div class="vault-item-info">
                    <h3 class="vault-item-name"><a href="{{object.get_absolute_url }}">{{ object }}</a></h3>
                </div>

            </div>
            {% endfor %}
     </div>

{% endblock content%}

videoservice/courses/templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}
{% load static %}

{% block post_detail_link %}

{% if object is not None %}
	<li><a href="{{ object.course.get_absolute_url }}">{{ object.course.title }}</a></li>
	<li>{{ object.title }}</li>
{% endif %}

{% endblock %}

{% block content %}
	<div class='container'>
		<div class='row'>
			<h4 class="lesson-sub">Do not rush through the video. Take your time and go through each lesson several times before you move on.
				Look below for comments or questions, or refer to the Short Stack for further help.
			</h4>
		</div>
		<br/>
<main>
	  <div class="container">
		 <div class="row">
		   <div class='col-md-12'>

		{% if object is not None %}
				 <h3>{{ object.title }}</h3>
					<p>{{ object.description }}</p>

						<video controls
									controlsList="nodownload"
									src="{{ object.video_url.url }}"
									width="640"
									height="360">
									Sorry, your browser doesnt support embedded
									video. You suck!
				</video>
			 </div>
		  </div>
	  </div>

	  {% else %}
				<h3>Upgrade membership</h3>
				<p>To view this course you'll need to upgrade your membership</p>
				<br>
				<a href="{% url 'memberships:select' %}"><button class="btn btn-warning">Check out memberships</button></a>
				<hr>
	 {% endif %}


  <section id="content2">

  </section>

</main>
<script src="{% static 'js/video.js' %}"></script>
{% endblock content %}

videoservice/courses/templates/courses/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

videoservice/courses/templates/courses/navbar.html
{% load static %}
<div class="container-fluid">
    <div class="top-nav">
     <div class="col-sm-2 col-md-2 col-lg-2">
         <img class="logo" src="https://s15.postimg.cc/dgcqp5jln/spectrum.png">
     </div>
     <div class="col-sm-4 col-md-4 col-lg-4">
         <a href="{% url 'home' %}">
            <i class="nav-icon fas fa-home fa-3x"></i>
        </a>
                    <a href="{% url 'courses:list' %}">
                        <i class="nav-icon fas fa-video fa-3x">
                        </i>
                    </a>
                    <a href="{% url 'blog:blog' %}">
                        <i class="nav-icon fab fa-stack-exchange fa-3x">
                        </i>
                    </a>
                </div>

                <div class="col-md-6 nav-auth">
                    <div id="nav-auth-wrap">
                      <div>
                          <h4 class="hello">Hello, {{ user.membership.first_name }}</h4>
                      </div>
                      <div>
                            {% if user.membership.avatar %}
                            <a href="/memberships/my_membership">
                              <img class="nav-user-av" src="{{ user.membership.avatar.url}}">
                            </a>
                            {% else %}
                            <a href="/memberships/my_membership">
                              <img class="nav-user-av" src="http://bootdey.com/img/Content/avatar/avatar6.png">
                            </a>
                            {% endif %}
                      </div>
                      <div class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                             <i class="fas fa-cog nav-settings fa-2x"></i>
                            </a>
                             <ul class="dropdown-menu">
                                <li class="nav-drop-i"><a href="/contact/">Contact</a></li>
                                <li class="nav-drop-i"><a href="{% url 'memberships:logout' %}">Logout</a></li>
                             </ul>
                          </div>
                     </div>
                </div>
    </div>
</div>